# Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR =  $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/ChatManager.cpp) \
                 $$quote($$BASEDIR/src/Home.cpp) \
                 $$quote($$BASEDIR/src/Setting.cpp) \
                 $$quote($$BASEDIR/src/applicationui.cpp) \
                 $$quote($$BASEDIR/src/main.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/ChatManager.hpp) \
                 $$quote($$BASEDIR/src/Home.hpp) \
                 $$quote($$BASEDIR/src/Setting.hpp) \
                 $$quote($$BASEDIR/src/applicationui.hpp)
    }

    CONFIG(release, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/ChatManager.cpp) \
                 $$quote($$BASEDIR/src/Home.cpp) \
                 $$quote($$BASEDIR/src/Setting.cpp) \
                 $$quote($$BASEDIR/src/applicationui.cpp) \
                 $$quote($$BASEDIR/src/main.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/ChatManager.hpp) \
                 $$quote($$BASEDIR/src/Home.hpp) \
                 $$quote($$BASEDIR/src/Setting.hpp) \
                 $$quote($$BASEDIR/src/applicationui.hpp)
    }
}

simulator {
    CONFIG(debug, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/ChatManager.cpp) \
                 $$quote($$BASEDIR/src/Home.cpp) \
                 $$quote($$BASEDIR/src/Setting.cpp) \
                 $$quote($$BASEDIR/src/applicationui.cpp) \
                 $$quote($$BASEDIR/src/main.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/ChatManager.hpp) \
                 $$quote($$BASEDIR/src/Home.hpp) \
                 $$quote($$BASEDIR/src/Setting.hpp) \
                 $$quote($$BASEDIR/src/applicationui.hpp)
    }
}

INCLUDEPATH +=  $$quote($$BASEDIR/src)

CONFIG += precompile_header

PRECOMPILED_HEADER =  $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES +=  $$quote($$BASEDIR/../src/*.c) \
             $$quote($$BASEDIR/../src/*.c++) \
             $$quote($$BASEDIR/../src/*.cc) \
             $$quote($$BASEDIR/../src/*.cpp) \
             $$quote($$BASEDIR/../src/*.cxx) \
             $$quote($$BASEDIR/../assets/*.qml) \
             $$quote($$BASEDIR/../assets/*.js) \
             $$quote($$BASEDIR/../assets/*.qs) \
             $$quote($$BASEDIR/../assets/componment/*.qml) \
             $$quote($$BASEDIR/../assets/componment/*.js) \
             $$quote($$BASEDIR/../assets/componment/*.qs) \
             $$quote($$BASEDIR/../assets/componment/home/*.qml) \
             $$quote($$BASEDIR/../assets/componment/home/*.js) \
             $$quote($$BASEDIR/../assets/componment/home/*.qs) \
             $$quote($$BASEDIR/../assets/componment/setting/*.qml) \
             $$quote($$BASEDIR/../assets/componment/setting/*.js) \
             $$quote($$BASEDIR/../assets/componment/setting/*.qs) \
             $$quote($$BASEDIR/../assets/data/*.qml) \
             $$quote($$BASEDIR/../assets/data/*.js) \
             $$quote($$BASEDIR/../assets/data/*.qs) \
             $$quote($$BASEDIR/../assets/images/*.qml) \
             $$quote($$BASEDIR/../assets/images/*.js) \
             $$quote($$BASEDIR/../assets/images/*.qs) \
             $$quote($$BASEDIR/../assets/screen/*.qml) \
             $$quote($$BASEDIR/../assets/screen/*.js) \
             $$quote($$BASEDIR/../assets/screen/*.qs)

    HEADERS +=  $$quote($$BASEDIR/../src/*.h) \
             $$quote($$BASEDIR/../src/*.h++) \
             $$quote($$BASEDIR/../src/*.hh) \
             $$quote($$BASEDIR/../src/*.hpp) \
             $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS =  $$quote($${TARGET}.ts)
